version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "max-article"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ucbfsopujsq0"
s3_prefix = "max-article"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
